application: Hello World Vane
version: 1
deploy: true
pub: true
dart2js: false 

handlers:
- url: /postData
  match: exact 
  script: hello_world.dart
  controller: PostData
  
- url: /getData
  match: exact 
  script: hello_world.dart
  controller: GetData

- url: /getDatas
  match: exact 
  script: hello_world.dart
  controller: GetDatas

# Static content  
- url: /
  match: postregex
  static_dir: web


